### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by cassolatto** [nategood/httpful#218]
I used this code:
<?php 
$token      = $_POST['token'];
$dataini    = $_POST['dataini'];
$datafin    = $_POST['datafin'];
$veiculo    = $_POST['veiculo'];
include('httpful.phar');

$url = "http://apiv1.multiportal.com.br:9870/veiculos/periodo";
    
$response = \Httpful\Request::post($url)
            ->expectsJson()
            ->addHeader('content-type','application/json')
            ->addHeader('token',$token)
            ->addHeader('dataInicial',$dataini)
            ->addHeader('dataFinal'  ,$datafin)  
            ->body('{"veiculo":"'.$veiculo.'}') 
            ->send();
echo $response;      
?>

and given me this error message ( long ):

"<br /> <b>Fatal error</b>: Uncaught exception 'Exception' with message 'Unable to parse response as JSON' in phar:///home/fastmobi/public_html/bredabus/httpful.phar/Httpful/Handlers/JsonHandler.php:30 Stack trace: #0 phar:///home/fastmobi/public_html/bredabus/httpful.phar/Httpful/Response.php(107): Httpful\Handlers\JsonHandler-&gt;parse('&lt;html&gt;&lt;body&gt;&lt;h1...') #1 phar:///home/fastmobi/public_html/bredabus/httpful.phar/Httpful/Response.php(46): Httpful\Response-&gt;_parse('&lt;html&gt;&lt;body&gt;&lt;h1...') #2 phar:///home/fastmobi/public_html/bredabus/httpful.phar/Httpful/Request.php(230): Httpful\Response-&gt;__construct('&lt;html&gt;&lt;body&gt;&lt;h1...', 'HTTP/1.1 400 Ba...', Object(Httpful\Request), Array) #3 /home/fastmobi/public_html/bredabus/mmposicaoveiculos.php(17): Httpful\Request-&gt;send() #4 {main} thrown in <b>phar:///home/fastmobi/public_html/bredabus/httpful.phar/Httpful/Handlers/JsonHandler.php</b> on line <b>30</b><br /> "

some help ?

Thanks in advance !

**Comment by bigbigant** [comment]
The serverside responses 400 error.

**Comment by cassolatto** [comment]
What this means ?

**Comment by bigbigant** [comment]
Just check the service http://apiv1.multiportal.com.br:9870/veiculos/periodo
It does't response a normal json entity. Instead of that the service reponses an error message and it's not a json.

**Comment by cassolatto** [comment]
thank you very much



*RICARDO CASSOLATTO*

Business Consultant
sintetik@gmail.com / 21 98196-0504

*FastMobile*
http://fastmobile.info
Rua Farani, 23 - apto. 403 - Botafogo - CEP 22231-020 - RJ - BRASIL

<http://www.facebook.com/ricardo.cassolatto>
<https://br.linkedin.com/in/ricardo-cassolato-9ba225>

2016-03-08 23:48 GMT-03:00 Qing Zhao <notifications@github.com>:
