### ISSUE TITLE
Why am i getting  Call to undefined function Httpful\curl_init() when using httpful.phar

### ISSUE THREAD

**Issue by ramosma** [nategood/httpful#244]
**When including the .phar and running the following:**
$url = "https://api.github.com/users/nategood";
$response = \Httpful\Request::get($url)
	->expectsJson()
	->withXTrivialHeader('Just as a demo')
	->send();
echo "{$response->body->name} joined GitHub on " .
                        date('M jS', strtotime($response->body->created_at)) ."\n";

**I get the following error:**
[22-Oct-2016 13:25:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Httpful\curl_init() in phar://D:/Lotus/Domino/data/domino/html/aotBadge/acclaim/httpful.phar/Httpful/Request.php:865
Stack trace:
#0 phar://D:/Lotus/Domino/data/domino/html/aotBadge/acclaim/httpful.phar/Httpful/Request.php(200): Httpful\Request->_curlPrep()
#1 D:\Lotus\Domino\data\domino\html\aotBadge\acclaim\badge_fetch.php(11): Httpful\Request->send()
#2 {main}
  thrown in phar://D:/Lotus/Domino/data/domino/html/aotBadge/acclaim/httpful.phar/Httpful/Request.php on line 865

**What am I missing?**

**Comment by nategood** [comment]
Interesting. What version of PHP are you using? I see what the issue is but
I'm surprised it hasn't been a problem to this point. Maybe there is a PHP
setting I am not aware of that affects the global namespace.

**Comment by MaitreDede** [comment]
Hi,
You need to activate the curl extension in your php.ini

**Comment by nategood** [comment]
Yep. That would make sense.
